//! Contract test over `data/players.ron` — the shipped player definitions.
//! AI/hub edits to the file fail here (fast, in CI) instead of breaking
//! rendering silently. Mirrors the invariants `roster.rs` unit tests pin.

use breakneck_baseball::game::appearance::{
    APPEARANCE_VERSION, Arms, CelebrationId, EMBEDDED_PLAYERS_RON, Eyewear, FidgetId, Headwear,
    RosterDefs, SkinTone, StanceId, TrotId, embedded_roster_file,
};
use breakneck_baseball::game::rules::LINEUP_SIZE;

#[test]
fn shipped_players_file_parses_and_validates() {
    let file = embedded_roster_file();
    assert_eq!(file.version, APPEARANCE_VERSION);
    RosterDefs::validate(&file).expect("data/players.ron violates a roster invariant");
}

#[test]
fn both_teams_field_nine_with_a_bench() {
    let file = embedded_roster_file();
    for pool in [&file.home, &file.away] {
        assert!(
            pool.len() > LINEUP_SIZE as usize,
            "need bench beyond the nine"
        );
    }
}

// ── Strict identifier check ─────────────────────────────────────────────────
//
// `#[serde(other)]` (see appearance.rs) means a mistyped id like
// `headwear: Helmit` parses fine as the default variant instead of failing —
// forward-compat for runtime, but a typo like that ships silently unless
// something checks the *written* identifiers against the *known* variant
// names. That's what this section does: it scans `data/players.ron`'s raw
// text (not the parsed `RosterFile`, which has already lost the distinction
// between "written and valid" and "written and silently defaulted") for every
// `<field>: <Identifier>` pair on an appearance field and rejects any
// identifier that isn't a real variant of that field's enum. The known-variant
// lists themselves (`SkinTone::NAMES` etc.) are generated by a macro next to
// each enum definition, from the same token list that defines the enum, so
// they cannot drift out of sync the way a hand-duplicated string list could.

/// (RON field key, that field's enum's known variant names).
fn known_fields() -> [(&'static str, &'static [&'static str]); 8] {
    [
        ("skin", SkinTone::NAMES),
        ("headwear", Headwear::NAMES),
        ("eyewear", Eyewear::NAMES),
        ("arms", Arms::NAMES),
        ("stance", StanceId::NAMES),
        ("fidget", FidgetId::NAMES),
        ("trot", TrotId::NAMES),
        ("celebration", CelebrationId::NAMES),
    ]
}

/// Reads a leading RON bare identifier (`[A-Za-z_][A-Za-z0-9_]*`) from the
/// start of `s`, if `s` starts with one.
fn read_identifier(s: &str) -> Option<&str> {
    let end = s
        .char_indices()
        .find(|(_, c)| !(c.is_alphanumeric() || *c == '_'))
        .map_or(s.len(), |(i, _)| i);
    let ident = &s[..end];
    let starts_alpha = ident.chars().next().is_some_and(|c| c.is_alphabetic());
    (!ident.is_empty() && starts_alpha).then_some(ident)
}

/// Scans `text` for every `<field>: <Identifier>` / `<field>: Some(<Identifier>)`
/// pair whose `<field>` is one of [`known_fields`], and returns a message for
/// each written identifier that isn't a known variant name of that field's
/// enum. An empty result means every appearance id actually written in
/// `text` is real.
fn unknown_identifiers(text: &str) -> Vec<String> {
    let mut problems = Vec::new();
    for (field, names) in known_fields() {
        let pat = format!("{field}:");
        let mut search_from = 0;
        while let Some(rel) = text[search_from..].find(&pat) {
            let key_pos = search_from + rel;
            let value_pos = key_pos + pat.len();
            search_from = value_pos;

            // Word-boundary guard: the byte right before the key must not be
            // an identifier character, else this match is the tail of some
            // longer identifier rather than an actual field key.
            if key_pos > 0 {
                let before = text.as_bytes()[key_pos - 1] as char;
                if before.is_alphanumeric() || before == '_' {
                    continue;
                }
            }

            let rest = text[value_pos..].trim_start();
            let Some(ident) = read_identifier(rest) else {
                continue; // a string, number, bool, or nested `(` — not ours
            };

            let variant = if ident == "Some" {
                let after_some = rest[ident.len()..].trim_start();
                let Some(inner) = after_some.strip_prefix('(') else {
                    continue;
                };
                match read_identifier(inner.trim_start()) {
                    Some(v) => v,
                    None => continue,
                }
            } else if ident == "None" {
                continue; // Option::None, not a variant identifier
            } else {
                ident
            };

            if !names.contains(&variant) {
                problems.push(format!(
                    "field {field:?}: identifier {variant:?} is not a known variant \
                     (expected one of {names:?})"
                ));
            }
        }
    }
    problems
}

#[test]
fn shipped_players_file_uses_only_known_appearance_identifiers() {
    let problems = unknown_identifiers(EMBEDDED_PLAYERS_RON);
    assert!(
        problems.is_empty(),
        "data/players.ron names appearance ids that aren't real variants \
         (a typo like `headwear: Helmit` parses fine via #[serde(other)] but \
         should fail this check instead of shipping silently):\n{}",
        problems.join("\n")
    );
}

#[test]
fn strict_identifier_check_catches_a_typo_in_every_appearance_field() {
    // A deliberately mistyped copy — one typo per field the check covers.
    // None of these are real variant names, so every one must be flagged.
    let bad = r#"(
        version: 1,
        home: [
            (name: "AAA", number: 1, appearance: (
                skin: Medim, headwear: Helmit, eyewear: Glases, arms: Wristband,
                style: (stance: Standrd, fidget: Some(BatTapp), trot: Standrd,
                    celebration: BatFlop),
            )),
        ],
        away: [ (name: "BBB", number: 2) ],
    )"#;
    let problems = unknown_identifiers(bad);
    assert_eq!(
        problems.len(),
        8,
        "expected one flagged typo per known field, got:\n{}",
        problems.join("\n")
    );
    for field in [
        "skin",
        "headwear",
        "eyewear",
        "arms",
        "stance",
        "fidget",
        "trot",
        "celebration",
    ] {
        assert!(
            problems.iter().any(|p| p.contains(&format!("{field:?}"))),
            "no problem reported for field {field:?}:\n{}",
            problems.join("\n")
        );
    }
}

#[test]
fn strict_identifier_check_accepts_every_real_variant() {
    // Sanity: one genuinely valid identifier per field must never be flagged
    // (guards the checker itself against false positives).
    let good = r#"(
        version: 1,
        home: [
            (name: "AAA", number: 1, appearance: (
                skin: Tan, headwear: Helmet, eyewear: Glasses, arms: WristbandL,
                style: (stance: OpenCrouch, fidget: Some(BatTap), trot: Standard,
                    celebration: BatFlip),
            )),
        ],
        away: [ (name: "BBB", number: 2) ],
    )"#;
    assert!(
        unknown_identifiers(good).is_empty(),
        "valid identifiers must not be flagged"
    );
}
